document.addEventListener('DOMContentLoaded', () => {
    const form = document.getElementById('roadmap-form');
    const topicInput = document.getElementById('topic-input');
    const generateBtn = document.getElementById('generate-btn');
    const loader = document.getElementById('loader');
    const roadmapContainer = document.getElementById('roadmap-container');
    const displayTopic = document.getElementById('display-topic');
    const timeline = document.getElementById('timeline');

    form.addEventListener('submit', async (e) => {
        e.preventDefault();
        const topic = topicInput.value.trim();
        if (!topic) return;

        // UI Reset
        roadmapContainer.classList.add('hidden');
        timeline.innerHTML = '';
        const existingError = document.querySelector('.error-message');
        if (existingError) existingError.remove();
        
        // Show Loading
        loader.classList.remove('hidden');
        generateBtn.disabled = true;
        
        try {
            // Attempt to fetch from our backend if running via app.py
            let response;
            try {
                response = await fetch('/api/roadmap', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ topic })
                });
            } catch (err) {
                // If backend is not running, we show a mock UI to demonstrate the beautiful layout
                console.warn("Backend not running or unreachable, using mock data for demonstration.");
                setTimeout(() => {
                    renderMockRoadmap(topic);
                    showRoadmapUI(topic);
                }, 2000);
                return;
            }

            if (response && response.ok) {
                const data = await response.json();
                const roadmapText = data.roadmap;
                const steps = parseRoadmapText(roadmapText);
                
                if (steps.length === 0) {
                    throw new Error("Could not parse the roadmap properly. Received: " + roadmapText.substring(0, 50) + "...");
                }

                renderSteps(steps);
                showRoadmapUI(topic);
            } else {
                let errorMsg = "Failed to generate roadmap.";
                try {
                    const errData = await response.json();
                    errorMsg = errData.error || errorMsg;
                } catch(e) {}
                throw new Error(errorMsg);
            }
        } catch (error) {
            console.error('Error:', error);
            showError("Oops! Couldn't generate the roadmap. " + error.message);
        }
    });

    function showRoadmapUI(topic) {
        loader.classList.add('hidden');
        generateBtn.disabled = false;
        displayTopic.innerHTML = `Your <span class="gradient-text">${topic}</span> Roadmap`;
        roadmapContainer.classList.remove('hidden');

        // Trigger animations for items sequentially
        setTimeout(() => {
            const items = document.querySelectorAll('.timeline-item');
            items.forEach((item, index) => {
                setTimeout(() => {
                    item.classList.add('visible');
                }, index * 150);
            });
        }, 100);
    }

    function showError(msg) {
        loader.classList.add('hidden');
        generateBtn.disabled = false;
        
        const errorDiv = document.createElement('div');
        errorDiv.className = 'error-message';
        errorDiv.textContent = msg;
        form.parentNode.insertBefore(errorDiv, form.nextSibling);
    }

    function parseRoadmapText(text) {
        // Parse markdown generated by Gemini based on the prompt:
        // "step name + a small description + two youtube link for reference , be short 7 to 8 steps is ok"
        
        const steps = [];
        // Generic split for numbers like '1.', '**1.**', 'Step 1' etc
        const blocks = text.split(/(?=\n(?:\*\*|\* )?\d+\.\s|\nstep\s\d+|\n\*\*step\s)/i);
        
        let stepCount = 1;
        
        blocks.forEach(block => {
            const trimmed = block.trim();
            if (!trimmed) return;
            
            const lines = trimmed.split('\n').map(l => l.trim()).filter(l => l.length > 0);
            if (lines.length === 0) return;
            
            // Extract title
            let title = lines[0].replace(/^(?:\*\*|\* )?\d+\.\s*|^\*\*step\s*\d+[:\.\-]?\s*/i, '').replace(/\*\*$/g, '').trim();
            if (title.length > 80) {
                title = title.substring(0, 80) + "...";
            }
            
            // Skip intro/outro if caught
            if (title.toLowerCase().includes("here is a roadmap") || title.toLowerCase().includes("sure")) {
                return;
            }

            const descriptionLines = [];
            const links = [];

            // Parse remaining lines for description and URLs
            for (let i = 1; i < lines.length; i++) {
                let line = lines[i];
                
                const urlMatch = line.match(/(https?:\/\/[^\s]+)/g);
                if (urlMatch) {
                    urlMatch.forEach(url => {
                        let cleanUrl = url.replace(/[\)\]]$/, '');
                        links.push(cleanUrl);
                        line = line.replace(url, '').trim();
                    });
                }
                
                // Clean up markdown list formatting
                line = line.replace(/^[\*\-]\s*/, '').replace(/\*\*([^\*]+)\*\*/g, '$1').trim();
                
                // Ignore empty lines or just "youtube link" labels
                if (line && !line.toLowerCase().match(/youtube links?[:\s]*$/)) {
                    descriptionLines.push(line);
                }
            }
            
            steps.push({
                num: stepCount++,
                title: title.replace(/\*\*/g, ''),
                desc: descriptionLines.join(' <br/> '),
                links: links.slice(0, 2)
            });
        });

        return steps;
    }

    function renderSteps(steps) {
        timeline.innerHTML = '';
        steps.forEach((step) => {
            timeline.appendChild(createTimelineItem(step.num, step.title, step.desc, step.links));
        });
    }

    function createTimelineItem(num, title, desc, links) {
        const item = document.createElement('div');
        item.className = 'timeline-item';
        
        let linksHTML = '';
        if (links && links.length > 0) {
            linksHTML = '<div class="step-links">';
            links.forEach((link, i) => {
                if(link.includes("youtube.com") || link.includes("youtu.be")) {
                    linksHTML += `<a href="${link}" target="_blank" class="yt-link"><i class="fa-brands fa-youtube"></i> Watch Video ${i+1}</a>`;
                } else {
                    linksHTML += `<a href="${link}" target="_blank" class="yt-link resource"><i class="fa-solid fa-link"></i> Resource ${i+1}</a>`;
                }
            });
            linksHTML += '</div>';
        } else {
            // Provide a direct YouTube search link as fallback
            linksHTML = `<div class="step-links">
                <a href="https://www.youtube.com/results?search_query=${encodeURIComponent(title)}" target="_blank" class="yt-link"><i class="fa-brands fa-youtube"></i> Search Video</a>
            </div>`;
        }

        item.innerHTML = `
            <div class="timeline-node">${num}</div>
            <div class="timeline-content">
                <h3 class="step-title">${title || ('Step ' + num)}</h3>
                <p class="step-description">${desc || 'Follow the resources to complete this stage of your journey.'}</p>
                ${linksHTML}
            </div>
        `;
        return item;
    }

    // High quality mock data for presentation when Python server is not active
    function renderMockRoadmap(topic) {
        const mockSteps = [
            {
                num: 1,
                title: `Introduction to ${topic}`,
                desc: `Discover the fundamental concepts, history, and core terminology of ${topic}. Get a high-level overview of why this field is important and how it impacts the real world.`,
                links: ["https://youtube.com/watch?v=mock1", "https://youtube.com/watch?v=mock2"]
            },
            {
                num: 2,
                title: 'Environment Setup & Basics',
                desc: 'Install the necessary tools, configure your development workspace, and write your first basic project or configuration to ensure everything is working correctly.',
                links: ["https://youtube.com/watch?v=mock3"]
            },
            {
                num: 3,
                title: 'Core Architecture & Patterns',
                desc: 'Dive deep into the underlying architecture and design patterns. Learn how different components interact and the industry best practices for structuring your work robustly.',
                links: ["https://youtube.com/watch?v=mock4", "https://example.com/docs"]
            },
            {
                num: 4,
                title: 'Advanced Features & Optimization',
                desc: 'Explore complex functionalities, algorithmic optimizations, and performance tuning strategies that distinguish intermediate users from beginners.',
                links: ["https://youtube.com/watch?v=mock5", "https://youtube.com/watch?v=mock6"]
            },
            {
                num: 5,
                title: 'Real-World Capstone Project',
                desc: 'Apply everything you have learned by building a comprehensive, end-to-end project that solves a practical problem to showcase in your portfolio.',
                links: ["https://youtube.com/watch?v=mock7"]
            }
        ];
        renderSteps(mockSteps);
    }
});
